% Wrapping data from ADRESS in format compatible with blobslicer
%
%   Input:  
%               data = struct data mat generated by 'loadadress.m'
%               fname = name of output file (.mat file)
%
%   Output:  
%               No output to workspace. Function only saves a file
%               'fname.mat' containing the 3D data matrix and scales
%               for axes in a structure compatible with "blobslicer.m"
%


function fromadress2blob(data,fname,varargin)

if numel(varargin)>0
    data=datacrop(data,1,[varargin{1,1},varargin{1,2}]);
else
end


toblobslicer(shiftdim(data.x,1),data.axes{1,2},data.axes{1,3},data.axes{1,1},fname);